/**
 * Efficient Labeling of Time Series
 * No description provided
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeSeriesSample } from './timeSeriesSample';


/**
 * TimeSeriesProject - a time series project samples: The samples of this TimeSeriesProject [Optional].
 */
export interface TimeSeriesProject { 
    samples?: Array<TimeSeriesSample>;
}

