/**
 * Efficient Labeling of Time Series
 * No description provided
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TimeSeries } from './timeSeries';


/**
 * TimeSeriesSample - a time series sample containing one or more time series id: The id of this TimeSeriesSample [Optional]. sample: The sample of this TimeSeriesSample [Optional]. sample_agg : The aggregated sample of this TimeSeriesSample [Optional].
 */
export interface TimeSeriesSample { 
    id?: number;
    sample?: Array<TimeSeries>;
}

